# Generated by Django 4.2.4 on 2023-10-14 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_id', models.CharField(max_length=20)),
                ('person_name', models.CharField(max_length=100)),
                ('person_email', models.EmailField(max_length=254)),
                ('person_contact', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'person',
            },
        ),
    ]
